# Generated by Django 5.2.1 on 2025-05-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('content', models.TextField()),
                ('content_file', models.FileField(blank=True, null=True, upload_to='projects/')),
            ],
        ),
    ]
