# Generated by Django 5.2.1 on 2025-06-09 03:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên dự án')),
                ('image_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Ảnh dự án (Tải lên từ máy tính)')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Ảnh dự án (URL từ Internet)')),
                ('area', models.IntegerField(blank=True, null=True, verbose_name='Diện tích (m²)')),
                ('investor', models.TextField(blank=True, null=True, verbose_name='Chủ đầu tư')),
                ('product', models.TextField(blank=True, null=True, verbose_name='Sản phẩm')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Thành phố')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
