# Generated by Django 5.2.1 on 2025-06-07 07:57

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='content',
        ),
        migrations.RemoveField(
            model_name='project',
            name='content_file',
        ),
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.TextField(blank=True, null=True, verbose_name='Diện tích'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Ảnh dự án (Tải lên từ máy tính)'),
        ),
        migrations.AddField(
            model_name='project',
            name='investor',
            field=models.TextField(blank=True, null=True, verbose_name='Chủ đầu tư'),
        ),
        migrations.AddField(
            model_name='project',
            name='product',
            field=models.TextField(blank=True, null=True, verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ảnh dự án (URL từ Internet)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên dự án'),
        ),
    ]
