# Generated by Django 5.2.1 on 2025-06-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_content_remove_project_content_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Thành phố'),
        ),
    ]
