# Generated by Django 5.2.1 on 2025-06-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='area',
            field=models.IntegerField(blank=True, null=True, verbose_name='Diện tích (m²)'),
        ),
    ]
