# Generated by Django 5.2.1 on 2025-06-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='investor_en',
            field=models.TextField(blank=True, null=True, verbose_name='Chủ đầu tư'),
        ),
        migrations.AddField(
            model_name='project',
            name='investor_ja',
            field=models.TextField(blank=True, null=True, verbose_name='Chủ đầu tư'),
        ),
        migrations.AddField(
            model_name='project',
            name='investor_vi',
            field=models.TextField(blank=True, null=True, verbose_name='Chủ đầu tư'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Tên dự án'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='Tên dự án'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_vi',
            field=models.CharField(max_length=255, null=True, verbose_name='Tên dự án'),
        ),
        migrations.AddField(
            model_name='project',
            name='product_en',
            field=models.TextField(blank=True, null=True, verbose_name='Sản phẩm'),
        ),
        migrations.AddField(
            model_name='project',
            name='product_ja',
            field=models.TextField(blank=True, null=True, verbose_name='Sản phẩm'),
        ),
        migrations.AddField(
            model_name='project',
            name='product_vi',
            field=models.TextField(blank=True, null=True, verbose_name='Sản phẩm'),
        ),
    ]
