# Generated by Django 5.2.1 on 2025-06-13 05:19

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Thể loại tin')),
                ('name_vi', models.CharField(max_length=100, null=True, unique=True, verbose_name='Thể loại tin')),
                ('name_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='Thể loại tin')),
                ('name_ja', models.CharField(max_length=100, null=True, unique=True, verbose_name='Thể loại tin')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('title_vi', models.CharField(max_length=200, null=True, verbose_name='Tiêu đề')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Tiêu đề')),
                ('title_ja', models.CharField(max_length=200, null=True, verbose_name='Tiêu đề')),
                ('published_at', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày đăng')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Nội dung')),
                ('content_vi', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Nội dung')),
                ('content_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Nội dung')),
                ('content_ja', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Nội dung')),
                ('image_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Ảnh tin tức (Tải lên từ máy tính)')),
                ('views', models.IntegerField(default=0, verbose_name='Lượt xem')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory', verbose_name='Thể loại')),
            ],
        ),
    ]
