# Generated by Django 5.2.1 on 2025-06-10 09:22

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Thể loại tin')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_file',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='news',
            name='summary',
        ),
        migrations.AddField(
            model_name='news',
            name='image_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Ảnh tin tức (Tải lên từ máy tính)'),
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Lượt xem'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày đăng'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề'),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory', verbose_name='Thể loại'),
        ),
    ]
