# Generated by Django 5.2.1 on 2025-06-10 16:23

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newscategory_remove_news_content_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Nội dung'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ja',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Nội dung'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_vi',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Nội dung'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Tiêu đề'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ja',
            field=models.CharField(max_length=200, null=True, verbose_name='Tiêu đề'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_vi',
            field=models.CharField(max_length=200, null=True, verbose_name='Tiêu đề'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Thể loại tin'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_ja',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Thể loại tin'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_vi',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Thể loại tin'),
        ),
    ]
