# Generated by Django 5.2.1 on 2025-06-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('BANK', 'Bank Transfer')], default='COD', max_length=50),
        ),
    ]
