# Generated by Django 5.2.1 on 2025-06-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank_proof',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
