# Generated by Django 5.2.1 on 2025-06-28 16:00

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên danh mục')),
                ('name_vi', models.CharField(max_length=255, null=True, verbose_name='Tên danh mục')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Tên danh mục')),
                ('name_ja', models.CharField(max_length=255, null=True, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('description_vi', tinymce.models.HTMLField(blank=True, null=True)),
                ('description_en', tinymce.models.HTMLField(blank=True, null=True)),
                ('description_ja', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm hoặc giải pháp')),
                ('name_vi', models.CharField(max_length=255, null=True, verbose_name='Tên sản phẩm hoặc giải pháp')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Tên sản phẩm hoặc giải pháp')),
                ('name_ja', models.CharField(max_length=255, null=True, verbose_name='Tên sản phẩm hoặc giải pháp')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Mô tả')),
                ('description_vi', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Mô tả')),
                ('description_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Mô tả')),
                ('description_ja', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Mô tả')),
                ('sold', models.IntegerField(blank=True, default=0, null=True, verbose_name='Số lượng đã bán')),
                ('unit', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Đơn vị tính')),
                ('stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='Số lượng còn lại')),
                ('sale_price', models.IntegerField(blank=True, default=-1, null=True, verbose_name='Giá khuyến mại (Nếu không có thì để trống)')),
                ('org_price', models.IntegerField(blank=True, default=-1, null=True, verbose_name='Giá niêm yết (Nếu không có thì để trống)')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('category', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Danh mục')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(null=True, upload_to='products/images/', verbose_name='File ảnh')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Link ảnh được tạo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
