# Generated by Django 5.2.1 on 2025-05-31 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc_file', models.FileField(blank=True, null=True, upload_to='descs/')),
                ('description', models.TextField()),
                ('sold', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('sale_price', models.FloatField()),
                ('org_price', models.FloatField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image_main', models.ImageField(upload_to='products/')),
                ('image_sub_1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_sub_2', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Categorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
