# Generated by Django 5.2.1 on 2025-06-05 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_description_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_main',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_sub_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_sub_2',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(null=True, upload_to='products/images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
