# Generated by Django 5.2.1 on 2025-06-07 08:38

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productimage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên danh mục'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên sản phẩm hoặc giải pháp'),
        ),
        migrations.AlterField(
            model_name='product',
            name='org_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Giá niêm yết'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Giá khuyến mại (Điền không có thì điền giá gốc)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Số lượng đã bán'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Số lượng còn lại'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_file',
            field=models.ImageField(null=True, upload_to='products/images/', verbose_name='File ảnh'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link ảnh được tạo'),
        ),
    ]
