# Generated by Django 5.2.1 on 2025-06-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_category_name_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(blank=True, default=-1, null=True, verbose_name='Giá khuyến mại (Nếu không có thì để trống)'),
        ),
    ]
